version: '3.1'
services:
  main-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stat-service
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - STAT_SERVER_URL=http://stat-service:9090

  main-db:
    image: postgres:14-alpine
    container_name: main-db

    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stat-service:
    build: stat-service/server
    image: stat-service
    container_name: stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat-db
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  stat-db:
    image: postgres:14-alpine
    container_name: stat-db
    environment:
      - POSTGRES_DB=stat-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
